#manipulator:
#  kinematics_solver: ur_kinematics/UR5eKinematicsPlugin
#  kinematics_solver_search_resolution: 0.005
#  kinematics_solver_timeout: 0.005
# kinematics_solver: ur_kinematics/UR5KinematicsPlugin
# kinematics_solver_search_resolution: 0.005
# kinematics_solver_timeout: 0.005
manipulator:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  solve_type: Distance
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
ur5e_arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.05
gripper:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.05
